version: '3'
services:
  web:
    image: owasp/modsecurity:nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/custom.conf:/etc/nginx/conf.d/custom.conf
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/modsec:/etc/nginx/modsec
      - ./app:/var/www/html
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    command: --default-authentication-plugin=mysql_native_password
